name: "EKS kubectl"
author: Ian Belcher
description: An action allowing you to integrate with EKS via kubectl in a Github Action, easily...
branding:
  color: "white"
  icon: "command"
runs:
  using: "docker"
  image: docker://shantkeh/eks-kubectl-action:1.0
inputs:
  cluster_name:
    description: The name of the cluster you're using
    required: true
  args:
    description: The arguments that you want to pass through to the kubectl command
    required: true
